extends:
  - eslint:recommended
  - plugin:react/recommended
plugins:
  - react
env:
  node: true
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
rules:
  react/prop-types: off
